name: Appium CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# permissions:
#   contents: read

jobs:
  build:
    runs-on: macos-latest # the machine type
    strategy: # we are using strategy if we need to run on parallel with different devices and version
      matrix:
        api-level: [29] #Google api level for example [25,23,28] 
        target: [playstore]
    steps:
    - uses: actions/checkout@v4 #checkout the code 

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        # maven-version: 3.8
          
    - name: Debug Environment
      run: |
        echo "PATH: $PATH"
        which java
        java -version

    # - name: Set Java 18 as Default
    #   run: echo 'export JAVA_HOME="/usr/libexec/java_home -v 19"' >> $GITHUB_ENV

    # - name: Debug Environment
    #   run: |
    #     echo "PATH: $PATH"
    #     which mvn

    # - name: Build with Maven
    #   run: mvn clean install -DskipTests=true

    - name: Install and Run Appium Server
      run: |
        chmod +x ./scripts/RunAppiumServer.sh # install and run appium server in the background
        npm install -g appium
        appium -v
        npm -g install npm
        npm i appium-uiautomator2-driver
        appium driver install uiautomator2
        appium > /dev/null &

    - name: Start Emulator
      run: emulator -avd emulator-29 -no-skin -no-audio -no-window -camera-back emulated -qemu -enable-kvm

    - name: Wait for Emulator
      run: |
        i=0
        while [ $i -le 180 ]; do
          adb wait-for-device
          sleep 1
          i=$((i + 1))
        done
      continue-on-error: true

    - name: Start Screen Recording
      run: adb shell screenrecord /sdcard/emulator-video.mp4

    - name: Run Your Test Suite
      run: mvn clean test -Pandroid

    - name: Stop Screen Recording
      run: adb shell pkill -2 -l 1 screenrecord

    - name: Pull Video Recording
      run: adb pull /sdcard/emulator-video.mp4 ${{ runner.workspace }}/emulator-video.mp4

    - name: Upload Video Recording
      uses: actions/upload-artifact@v2
      with:
        name: emulator-video
        path: ${{ runner.workspace }}/emulator-video.mp4